[tool.ruff]
line-length = 120
# Target Python version
target-version = "py310"

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
]
ignore = [
  # Allow longer lines occasionally in tests/README; but we keep global line-length at 120
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
